version: '3.8'

services:
  app:
    build: .
    container_name: app-report-hub
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  db:
    image: mysql:8.0
    container_name: db-report-hub
    environment:
      - MYSQL_ROOT_PASSWORD=secret123
      - MYSQL_DATABASE=report_hub
      - MYSQL_USER=reportuser
      - MYSQL_PASSWORD=secret123
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: rabbitmq-report-hub
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  db-data:
